-- Please provide a SQL statement for each question
-- 1) Write a query to get the sum of impressions by day.
SELECT 
	date,
	SUM(impressions) AS total_impressions
FROM 
	marketing_data
GROUP BY
	date
ORDER BY
	date ASC

-- 2) Write a query to get the top three revenue-generating states in order of best to worst. How much revenue did the third best state generate?
SELECT
	state,
	SUM(revenue) AS total_revenue
FROM
	website_revenue
GROUP BY
	state
ORDER BY
	total_revenue DESC
LIMIT 3

-- The third best state was Ohio generating $37,577 in revenue.

-- 3) Write a query that shows total cost, impressions, clicks, and revenue of each campaign. Make sure to include the campaign name in the output.
SELECT 
	c.name,
	q1.*
FROM
	campaign_info c
JOIN (
SELECT
	w.campaign_id AS campaign_id,
    CAST(ROUND(SUM(m.cost), 2) as decimal(10, 2)) AS total_cost,
    SUM(m.impressions) AS total_impressions,
    SUM(m.clicks) AS total_clicks,
    SUM(w.revenue) AS total_revenue
FROM 
	marketing_data m
JOIN 
	website_revenue w
ON
	m.campaign_id = w.campaign_id
GROUP BY
	campaign_id
) q1
ON
	c.id = q1.campaign_id
ORDER BY
	c.name

-- 4) Write a query to get the number of conversions of Campaign5 by state. Which state generated the most conversions for this campaign?
SELECT
	RIGHT(geo, 2) AS state,
    SUM(conversions) AS total_conversions
FROM (
	SELECT
	c.name,
    m.*
FROM
	marketing_data m
LEFT JOIN
	campaign_info c
ON
	m.campaign_id = c.id
) q1
WHERE
	name = 'Campaign5'
GROUP BY 
	state
ORDER BY
	total_conversions DESC

-- For campaign 5, the most conversions were generated by Georgia with 672 conversions.

-- 5) In your opinion, which campaign was the most efficient, and why?
SELECT 
	c.name,
	q1.*,
    ROUND((total_clicks / total_impressions), 2) AS click_through_rate,
    ROUND((total_conversions/ total_impressions), 2) AS impression_to_conversion_rate,
    ROUND((total_revenue/ total_conversions), 2) AS revenue_per_conversion,
    ROUND((total_revenue/ total_impressions), 2) AS revenue_per_impressions,
    (total_revenue - total_cost) AS total_profit,
    ROUND(((total_revenue - total_cost) / (total_cost)) * 100, 2) AS percent_return
FROM
	campaign_info c
JOIN (
SELECT
	w.campaign_id AS campaign_id,
    CAST(ROUND(SUM(m.cost), 2) as decimal(10, 2)) AS total_cost,
    SUM(m.impressions) AS total_impressions,
    SUM(m.clicks) AS total_clicks,
    SUM(m.conversions) AS total_conversions,
    SUM(w.revenue) AS total_revenue,
    MIN(m.date) AS first_marketing_date,
    MIN(w.date) AS first_website_revenue_date,
    MAX(m.date) AS last_marketing_date,
    MAX(w.date) AS last_website_revenue_date
FROM 
	marketing_data m
JOIN 
	website_revenue w
ON
	m.campaign_id = w.campaign_id
GROUP BY
	campaign_id
) q1
ON
	c.id = q1.campaign_id
ORDER BY
	c.name

-- Great Question. My first thought would be Campaign 3 becuase the total profit is much higher than the other campaigns. 
-- The only problem with such quick thinking is that there are other factors to consider. The dates do not all match up for 
-- running the campaign and some campaigns were run in states others were not, this leads me to believe that
-- proper AB Testing was not performed meaning that there is no guarantee of sample demographics being comparable 
-- across campaigns. This could mean campaign3 was run in a major city while the other campaigns were maybe run in a less major 
-- city of the specified states. Also looking at the next question, we see that the campaigns were not all run on all the same days. 
-- This would make it difficult to say that Campaign3 was outright more efficient if it had such an advantage. 
-- Also, Campaign5 might have a technical error because the total_clicks is higher than total_impressions, which does not make logical sense. 
-- It is also worth noting that some campaigns are 'enabled' and others are 'paused' and it is not clarified 
-- what exactly that means in this case and if it plays into any of the results. To make a data driven decision on efficiency of the campaigns,
-- I would want some of these holes filled in and to have a guarantee of AB Testing 
-- standards followed. With limited information, I would conclude that campaign3 was the most efficient solely based on total profit. 

--Bonus Question
-- 6) Write a query that showcases the best day of the week (e.g., Sunday, Monday, Tuesday, etc.) to run ads.

-- By Campaign then day of week
SELECT 
	c.name,
	q1.*
FROM
	campaign_info c
JOIN (
SELECT
	w.campaign_id AS campaign_id,
    CAST(ROUND(SUM(m.cost), 2) as decimal(10, 2)) AS total_cost,
    SUM(m.impressions) AS total_impressions,
    SUM(m.clicks) AS total_clicks,
    SUM(w.revenue) AS total_revenue,
    DAYNAME(m.date) AS day_of_the_week
FROM 
	marketing_data m
JOIN 
	website_revenue w
ON
	m.campaign_id = w.campaign_id
GROUP BY
	campaign_id, day_of_the_week
) q1
ON
	c.id = q1.campaign_id
ORDER BY
	c.name,
	CASE
          WHEN day_of_the_week = 'Sunday' THEN 1
          WHEN day_of_the_week = 'Monday' THEN 2
          WHEN day_of_the_week = 'Tuesday' THEN 3
          WHEN day_of_the_week = 'Wednesday' THEN 4
          WHEN day_of_the_week = 'Thursday' THEN 5
          WHEN day_of_the_week = 'Friday' THEN 6
          WHEN day_of_the_week = 'Saturday' THEN 7
     END ASC

-- BY Day of week only
SELECT
	DAYNAME(m.date) AS day_of_the_week,
    CAST(ROUND(SUM(m.cost), 2) as decimal(10, 2)) AS total_cost,
    SUM(m.impressions) AS total_impressions,
    SUM(m.clicks) AS total_clicks,
    SUM(m.conversions) AS total_conversions,
    SUM(w.revenue) AS total_revenue,
    ROUND(SUM(w.revenue) - SUM(m.cost), 2) AS total_profit,
    (SELECT COUNT(*) FROM marketing_data WHERE DAYNAME(date) = day_of_the_week) AS day_count
FROM 
	marketing_data m
JOIN 
	website_revenue w
ON
	m.campaign_id = w.campaign_id
GROUP BY
	day_of_the_week
ORDER BY
	total_profit DESC

-- Looking at these two tables, we see from the Day of week alone the best day to run ads is Friday with the highest
-- total_impressions, total_clicks, total_conversions, total_revenue and total_profit. It also still manages to not be
-- the highest cost (2nd highest) despite performing well in all of those KPI's. There is some factors that still
-- should be considered, once I added in the day_count column, we learn that Friday was also ran more often that the other
-- day of the weeks. This calls into question the ideology that was stated in the previous question about AB Testing and having
-- consistency in the samples of the campaigns being run and the days of the week being run to have accurate results
-- to truly confirm if a day of the week is best/ if a campaign is best. Friday is likely the best day of the week to run ads,
-- but without standardizing these other variables, we can not make that conclusion that there is a statistically signifcant 
-- improvemnt compared to other days of the week. Some more helpful qualititative information could also be the type of product
-- being advertised and the typically audience that purchases said product. Advertising pet food to a family with 4 dogs might
-- make more sense to advertise on Sunday morning when a larger proportion of families go shopping for the week, but advertising beer/ seltzers
-- to a college student might make more sense to advertise to on a Friday evening. This being said, quantitative and qualitative 
-- data should be taken into consideration when making advertising decisions
